site_name:        GeniePlugins.jl
repo_url:         https://github.com/GenieFramework/GeniePlugins.jl
site_description: Creating Plugins for Genie.jl
site_author:      Adrian Salceanu

theme: readthedocs

extra_css:
  - assets/Documenter.css

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math

docs_dir: 'build'

pages:
  - Home: index.md
